[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[profile.release]
lto = true
codegen-units = 1

[[bench]]
name = "day1"
harness = false

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }
